// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: calculator/proto/calculate.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateRequest) Reset() {
	*x = CalculateRequest{}
	mi := &file_calculator_proto_calculate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRequest) ProtoMessage() {}

func (x *CalculateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_calculate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return file_calculator_proto_calculate_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CalculateRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type CalculateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sum           int32                  `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateResponse) Reset() {
	*x = CalculateResponse{}
	mi := &file_calculator_proto_calculate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateResponse) ProtoMessage() {}

func (x *CalculateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_calculate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateResponse.ProtoReflect.Descriptor instead.
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return file_calculator_proto_calculate_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateResponse) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

var File_calculator_proto_calculate_proto protoreflect.FileDescriptor

const file_calculator_proto_calculate_proto_rawDesc = "" +
	"\n" +
	" calculator/proto/calculate.proto\x12\tcalculate\".\n" +
	"\x10CalculateRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"%\n" +
	"\x11CalculateResponse\x12\x10\n" +
	"\x03sum\x18\x01 \x01(\x05R\x03sum2Z\n" +
	"\x10CalculateService\x12F\n" +
	"\tCalculate\x12\x1b.calculate.CalculateRequest\x1a\x1c.calculate.CalculateResponseB\x0fZ\rsumgrps/protob\x06proto3"

var (
	file_calculator_proto_calculate_proto_rawDescOnce sync.Once
	file_calculator_proto_calculate_proto_rawDescData []byte
)

func file_calculator_proto_calculate_proto_rawDescGZIP() []byte {
	file_calculator_proto_calculate_proto_rawDescOnce.Do(func() {
		file_calculator_proto_calculate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculator_proto_calculate_proto_rawDesc), len(file_calculator_proto_calculate_proto_rawDesc)))
	})
	return file_calculator_proto_calculate_proto_rawDescData
}

var file_calculator_proto_calculate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_calculator_proto_calculate_proto_goTypes = []any{
	(*CalculateRequest)(nil),  // 0: calculate.CalculateRequest
	(*CalculateResponse)(nil), // 1: calculate.CalculateResponse
}
var file_calculator_proto_calculate_proto_depIdxs = []int32{
	0, // 0: calculate.CalculateService.Calculate:input_type -> calculate.CalculateRequest
	1, // 1: calculate.CalculateService.Calculate:output_type -> calculate.CalculateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_proto_calculate_proto_init() }
func file_calculator_proto_calculate_proto_init() {
	if File_calculator_proto_calculate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculator_proto_calculate_proto_rawDesc), len(file_calculator_proto_calculate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_proto_calculate_proto_goTypes,
		DependencyIndexes: file_calculator_proto_calculate_proto_depIdxs,
		MessageInfos:      file_calculator_proto_calculate_proto_msgTypes,
	}.Build()
	File_calculator_proto_calculate_proto = out.File
	file_calculator_proto_calculate_proto_goTypes = nil
	file_calculator_proto_calculate_proto_depIdxs = nil
}
