apiVersion: {{ .Group }}/{{.CrdVersion}}
kind: {{.Kind}}
metadata:
  labels:
{{- range .Labels}}
    {{.Key}}: {{.Value}}
{{- end}}
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  image: "{{.Image}}"
  version: "{{.Version}}"
  port: {{.Port}}
  replicas: {{.Replicas}}
  ingressType: {{.IngressType}} 
  envoyGateway: {{.EnvoyGateway}}
  envoyGatewayNamespace: {{.EnvoyGatewayNamespace}}
  {{- if .IngressHostName }}
  ingressHostName: "{{.IngressHostName}}"
  {{- end }}
  {{- if .ImagePullSecret}}
  imagePullSecret: {{.ImagePullSecret}}
  {{- end }}
  imagepullPolicy: {{.ImagePullPolicy}}
  serviceAccount: {{.ServiceAccount}}
  resources:
    limits:
      cpu: {{.Resources.Limits.CPU}}
      memory: {{.Resources.Limits.Memory}}
{{- if .Resources.Limits.EphemeralStorage}}
      ephemeral-storage: {{.Resources.Limits.EphemeralStorage}}
{{- end}}
    requests:
      cpu: {{.Resources.Requests.CPU}}
      memory: {{.Resources.Requests.Memory}}
  startupProbe:
    httpGet:
      path: "{{.StartupProbe.HTTPGet.Path}}"
      port: {{.StartupProbe.HTTPGet.Port}}
    failureThreshold: {{.StartupProbe.FailureThreshold}}
    periodSeconds: {{.StartupProbe.PeriodSeconds}} 
  podSecurityContext:
    runAsNonRoot: {{.PodSecurityContext.RunAsNonRoot}}
    runAsUser: {{.PodSecurityContext.RunAsUser}}
    runAsGroup: {{.PodSecurityContext.RunAsGroup}}
    fsGroup: {{.PodSecurityContext.FSGroup}}
{{- if .Affinity}}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: {{ index (index (index (index .Affinity "nodeAffinity") "requiredDuringSchedulingIgnoredDuringExecution") "nodeSelectorTerms" 0) "matchExpressions" 0 "key" }}
                operator: {{ index (index (index (index .Affinity "nodeAffinity") "requiredDuringSchedulingIgnoredDuringExecution") "nodeSelectorTerms" 0) "matchExpressions" 0 "operator" }}
                values:
                  {{- range (index (index (index (index .Affinity "nodeAffinity") "requiredDuringSchedulingIgnoredDuringExecution") "nodeSelectorTerms" 0) "matchExpressions" 0 "values") }}
                  - {{ . }}
                  {{- end }}
{{- else}}
  affinity: {}
{{- end}}
{{- if .Tolerations}}
  tolerations:
{{- range .Tolerations}}
  - 
{{- range $key, $value := .}}
    {{$key}}: {{$value}}
{{- end}}
{{- end}}
{{- else}}
  tolerations: []
{{- end}}
