// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: blog/proto/blog.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blog) Reset() {
	*x = Blog{}
	mi := &file_blog_proto_blog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog) ProtoMessage() {}

func (x *Blog) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_blog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog.ProtoReflect.Descriptor instead.
func (*Blog) Descriptor() ([]byte, []int) {
	return file_blog_proto_blog_proto_rawDescGZIP(), []int{0}
}

func (x *Blog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Blog) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Blog) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Blog) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type BlogId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogId) Reset() {
	*x = BlogId{}
	mi := &file_blog_proto_blog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogId) ProtoMessage() {}

func (x *BlogId) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_blog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogId.ProtoReflect.Descriptor instead.
func (*BlogId) Descriptor() ([]byte, []int) {
	return file_blog_proto_blog_proto_rawDescGZIP(), []int{1}
}

func (x *BlogId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_blog_proto_blog_proto protoreflect.FileDescriptor

const file_blog_proto_blog_proto_rawDesc = "" +
	"\n" +
	"\x15blog/proto/blog.proto\x1a\x1bgoogle/protobuf/empty.proto\"c\n" +
	"\x04Blog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"\x18\n" +
	"\x06BlogId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xd0\x01\n" +
	"\vBlogService\x12\x1c\n" +
	"\n" +
	"CreateBlog\x12\x05.Blog\x1a\a.BlogId\x12\x1a\n" +
	"\bReadBlog\x12\a.BlogId\x1a\x05.Blog\x12+\n" +
	"\n" +
	"UpdateBlog\x12\x05.Blog\x1a\x16.google.protobuf.Empty\x12-\n" +
	"\n" +
	"DeleteBlog\x12\a.BlogId\x1a\x16.google.protobuf.Empty\x12+\n" +
	"\bListBlog\x12\x16.google.protobuf.Empty\x1a\x05.Blog0\x01BPZNgithub.com/dkr290/go-advanced-projects/protobuf-test/grpc-go-course/blog/protob\x06proto3"

var (
	file_blog_proto_blog_proto_rawDescOnce sync.Once
	file_blog_proto_blog_proto_rawDescData []byte
)

func file_blog_proto_blog_proto_rawDescGZIP() []byte {
	file_blog_proto_blog_proto_rawDescOnce.Do(func() {
		file_blog_proto_blog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_proto_blog_proto_rawDesc), len(file_blog_proto_blog_proto_rawDesc)))
	})
	return file_blog_proto_blog_proto_rawDescData
}

var file_blog_proto_blog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blog_proto_blog_proto_goTypes = []any{
	(*Blog)(nil),          // 0: Blog
	(*BlogId)(nil),        // 1: BlogId
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_blog_proto_blog_proto_depIdxs = []int32{
	0, // 0: BlogService.CreateBlog:input_type -> Blog
	1, // 1: BlogService.ReadBlog:input_type -> BlogId
	0, // 2: BlogService.UpdateBlog:input_type -> Blog
	1, // 3: BlogService.DeleteBlog:input_type -> BlogId
	2, // 4: BlogService.ListBlog:input_type -> google.protobuf.Empty
	1, // 5: BlogService.CreateBlog:output_type -> BlogId
	0, // 6: BlogService.ReadBlog:output_type -> Blog
	2, // 7: BlogService.UpdateBlog:output_type -> google.protobuf.Empty
	2, // 8: BlogService.DeleteBlog:output_type -> google.protobuf.Empty
	0, // 9: BlogService.ListBlog:output_type -> Blog
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blog_proto_blog_proto_init() }
func file_blog_proto_blog_proto_init() {
	if File_blog_proto_blog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_proto_blog_proto_rawDesc), len(file_blog_proto_blog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_proto_blog_proto_goTypes,
		DependencyIndexes: file_blog_proto_blog_proto_depIdxs,
		MessageInfos:      file_blog_proto_blog_proto_msgTypes,
	}.Build()
	File_blog_proto_blog_proto = out.File
	file_blog_proto_blog_proto_goTypes = nil
	file_blog_proto_blog_proto_depIdxs = nil
}
