### Shared
# @grpc-plaintext
# @grpc-import-path ../proto
# @grpc-proto main.proto

GRPC localhost:50051 main.TeachersService/GetTeachers 
Content-Type: application/json

{
  "teacher": {
    "class": "8C",
    "subject": "English"
  },
  "sort_by": [
    {
      "field": "last_name",
      "order": "ORDER_ASC_UNSPECIFIED"
    },
    {
      "field": "first_name",
      "order": "ORDER_DESC"
    }
  ]
}

