POST http://localhost:8080/events
Content-Type: "application/json"
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMUBleGFtcGxlLmNvbSIsImV4cCI6MTcxMTQwMzE5NSwidXNlcklkIjoyfQ.N9Z05kX1G6T5y63ocjmZwcCg8LPFQKZYd-wmjiOHrOU


{
  "name": "Text Event!!!",
  "description": "Another test 332!event",
  "location": "A test location332!",
  "datetime": "2025-01-01T15:30:00.000Z"  
}
