DELETE  http://localhost:8080/events/12
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzM0BleGFtcGxlLmNvbSIsImV4cCI6MTcxMDcxNDk0NywidXNlcklkIjo0fQ.W3huKrFS6cy4Ihj4d9qsr3JvCxYAitXEAtazNu0Jvqk
