name: Docker build and push CI

on:
  push:
    paths:
      - "api-service/**"
      - "internal-pypi/**"

    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build-api-service:
    uses: dkr290/go-advanced-projects/.github/workflows/docker-build-template.yml@main
    with:
      name: Build and push API-Service docker image
      docker_image_name: ghcr.io/${{ github.repository }}/api-service
      version: "0.0.1"
      folder: api-service/zarf/docker
      dockerfileName: Dockerfile.service

  build-pypi-service:
    uses: dkr290/go-advanced-projects/.github/workflows/docker-build-template.yml@main
    with:
      name: Build and push PYPI-Service docker image
      docker_image_name: ghcr.io/${{ github.repository }}/internal-pypi
      version: "0.0.1"
      folder: internal-pypi

  build-go-tasks-frontend-service:
    uses: dkr290/go-advanced-projects/.github/workflows/docker-build-template.yml@main
    with:
      name: Build and push go-tasks-frontend-Service docker image
      docker_image_name: ghcr.io/${{ github.repository }}/go-tasks-frontend
      version: "0.0.1"
      folder: go-templ-cruid-microservice/frontend

  build-go-tasks-backend-service:
    uses:
      dkr290/go-advanced-projects/.github/workflows/docker-build-template.yml@main

      # The type of runner that the job will run on
    with:
      docker_image_name: ghcr.io/${{ github.repository }}/go-tasks-backend
      version: "0.0.1"
      folder: go-templ-cruid-microservice/backend
      name: "Build and push go-tasks-backend-Service docker image"
