// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: payment.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PamentService_Payment_FullMethodName = "/payments.PamentService/Payment"
)

// PamentServiceClient is the client API for PamentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PamentServiceClient interface {
	Payment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PaymentResponse], error)
}

type pamentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPamentServiceClient(cc grpc.ClientConnInterface) PamentServiceClient {
	return &pamentServiceClient{cc}
}

func (c *pamentServiceClient) Payment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PaymentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PamentService_ServiceDesc.Streams[0], PamentService_Payment_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PaymentRequest, PaymentResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PamentService_PaymentClient = grpc.ServerStreamingClient[PaymentResponse]

// PamentServiceServer is the server API for PamentService service.
// All implementations must embed UnimplementedPamentServiceServer
// for forward compatibility.
type PamentServiceServer interface {
	Payment(*PaymentRequest, grpc.ServerStreamingServer[PaymentResponse]) error
	mustEmbedUnimplementedPamentServiceServer()
}

// UnimplementedPamentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPamentServiceServer struct{}

func (UnimplementedPamentServiceServer) Payment(*PaymentRequest, grpc.ServerStreamingServer[PaymentResponse]) error {
	return status.Error(codes.Unimplemented, "method Payment not implemented")
}
func (UnimplementedPamentServiceServer) mustEmbedUnimplementedPamentServiceServer() {}
func (UnimplementedPamentServiceServer) testEmbeddedByValue()                       {}

// UnsafePamentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PamentServiceServer will
// result in compilation errors.
type UnsafePamentServiceServer interface {
	mustEmbedUnimplementedPamentServiceServer()
}

func RegisterPamentServiceServer(s grpc.ServiceRegistrar, srv PamentServiceServer) {
	// If the following call panics, it indicates UnimplementedPamentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PamentService_ServiceDesc, srv)
}

func _PamentService_Payment_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PaymentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PamentServiceServer).Payment(m, &grpc.GenericServerStream[PaymentRequest, PaymentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PamentService_PaymentServer = grpc.ServerStreamingServer[PaymentResponse]

// PamentService_ServiceDesc is the grpc.ServiceDesc for PamentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PamentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payments.PamentService",
	HandlerType: (*PamentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Payment",
			Handler:       _PamentService_Payment_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "payment.proto",
}
